#!/bin/bash
set -e

CONTAINER_NAME="frontiersai-bot"
TEMP_DATA_DIR=".tmpdata"
PORT="${PORT:-8080}"
SETUP_PASSWORD="${SETUP_PASSWORD:-test}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Remove docker container if it exists
if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
  echo "Stopping and removing container '${CONTAINER_NAME}'..."
  docker rm -f "$CONTAINER_NAME"
else
  echo "No container '${CONTAINER_NAME}' found."
fi

# Clear temp data folder if it exists
if [ -d "$TEMP_DATA_DIR" ]; then
  echo "Removing ${TEMP_DATA_DIR}..."
  rm -rf "$TEMP_DATA_DIR"
else
  echo "No ${TEMP_DATA_DIR} folder found."
fi

# Build the container
echo "Building docker image..."
docker build -t frontiers-bot .

# Run the container
echo "Starting container '${CONTAINER_NAME}'..."
docker run -d --name "$CONTAINER_NAME" \
  -p "${PORT}:${PORT}" \
  -e PORT="$PORT" \
  -e SETUP_PASSWORD="$SETUP_PASSWORD" \
  -e OPENCLAW_STATE_DIR=/data/.openclaw \
  -e OPENCLAW_WORKSPACE_DIR=/data/workspace \
  -v "$(pwd)/${TEMP_DATA_DIR}:/data" \
  frontiers-bot

# Wait for the server to be ready
echo "Waiting for server to be ready..."
MAX_WAIT=60
WAITED=0
until curl -sf "http://localhost:${PORT}/setup/api/status" \
  -u ":${SETUP_PASSWORD}" > /dev/null 2>&1; do
  sleep 2
  WAITED=$((WAITED + 2))
  if [ "$WAITED" -ge "$MAX_WAIT" ]; then
    echo "ERROR: Server did not become ready after ${MAX_WAIT}s"
    echo "Container logs:"
    docker logs "$CONTAINER_NAME"
    exit 1
  fi
done
echo "Server ready after ~${WAITED}s."

# Helper to run openclaw commands inside the container
oclaw() {
  docker exec "$CONTAINER_NAME" \
    env OPENCLAW_STATE_DIR=/data/.openclaw OPENCLAW_WORKSPACE_DIR=/data/workspace \
    node /openclaw/dist/entry.js "$@"
}

# Read the gateway token generated by the server on startup
GATEWAY_TOKEN=$(docker exec "$CONTAINER_NAME" cat /data/.openclaw/gateway.token 2>/dev/null || echo "")
if [ -z "$GATEWAY_TOKEN" ]; then
  echo "WARNING: Could not read gateway token, generating fallback..."
  GATEWAY_TOKEN=$(openssl rand -hex 32)
fi

# Run openclaw onboard with default configs
echo "Running openclaw onboard..."
oclaw onboard \
  --non-interactive \
  --accept-risk \
  --json \
  --no-install-daemon \
  --skip-health \
  --workspace /data/workspace \
  --gateway-bind loopback \
  --gateway-port 18789 \
  --gateway-auth token \
  --gateway-token "$GATEWAY_TOKEN" \
  --flow quickstart

echo "Configuring gateway settings..."
oclaw config set gateway.controlUi.allowInsecureAuth true
oclaw config set gateway.auth.token "$GATEWAY_TOKEN"
oclaw config set --json gateway.trustedProxies '["127.0.0.1"]'

echo "Onboarding complete."

# Run workspace sync
echo "Running workspace sync..."
bash "$SCRIPT_DIR/sync-workspace.sh"

echo "Done. Container '${CONTAINER_NAME}' is running on port ${PORT}."
