import { confirm, text, note, log, spinner } from "@clack/prompts";
import { existsSync, readFileSync, writeFileSync, mkdirSync, chmodSync } from "node:fs";
import { resolve } from "node:path";
import { guardCancel, pollHealth, execFileAsync } from "../lib/utils.mjs";
import { ROOT, CONTAINER_NAME } from "../lib/constants.mjs";

const OPENCLAW_JSON = resolve(ROOT, ".tmpdata", ".openclaw", "openclaw.json");

const IMSG_CLI_PATH = "/data/scripts/imsg-ssh";
const DEFAULT_DB_PATH_SUFFIX = "/Library/Messages/chat.db";

// SSH paths on the persistent volume (survives container restarts)
const SSH_DIR = "/data/.ssh";
const SSH_KEY = `${SSH_DIR}/id_ed25519`;
const SSH_KNOWN_HOSTS = `${SSH_DIR}/known_hosts`;

// Local volume mirror of SSH_DIR (for reading the public key from the host)
const LOCAL_SSH_DIR = resolve(ROOT, ".tmpdata", ".ssh");

/**
 * Run a command inside the container as the openclaw user.
 */
async function dockerExec(cmd, timeoutMs = 15_000) {
  return execFileAsync(
    "docker",
    ["exec", CONTAINER_NAME, "su", "-", "openclaw", "-c", cmd],
    { timeout: timeoutMs }
  );
}

/**
 * Generate an SSH key pair inside the container if one doesn't already exist.
 * Returns the public key string.
 */
async function ensureSshKey() {
  // Check if key already exists
  try {
    const { stdout } = await dockerExec(`cat ${SSH_KEY}.pub`);
    if (stdout.trim()) return stdout.trim();
  } catch {}

  // Create SSH directory with proper permissions
  await dockerExec(`mkdir -p ${SSH_DIR} && chmod 700 ${SSH_DIR}`);

  // Generate ed25519 key (no passphrase)
  await dockerExec(
    `ssh-keygen -t ed25519 -f ${SSH_KEY} -N "" -C "openclaw@frontiersai-bot"`,
    20_000
  );

  const { stdout } = await dockerExec(`cat ${SSH_KEY}.pub`);
  return stdout.trim();
}

/**
 * Test SSH connectivity from the container to the remote Mac.
 * Uses StrictHostKeyChecking=accept-new to auto-accept on first connect.
 */
async function testSshConnectivity(remoteHost) {
  const sshOpts = [
    `-o StrictHostKeyChecking=accept-new`,
    `-o UserKnownHostsFile=${SSH_KNOWN_HOSTS}`,
    `-o ConnectTimeout=10`,
    `-i ${SSH_KEY}`,
  ].join(" ");

  // Test basic SSH + verify imsg is installed
  const { stdout } = await dockerExec(
    `ssh ${sshOpts} ${remoteHost} "export PATH=/opt/homebrew/bin:/usr/local/bin:\\$PATH; which imsg && imsg chats --limit 1 --json 2>/dev/null || echo __IMSG_NOT_FOUND__"`,
    30_000
  );
  return stdout;
}

/**
 * Create the imsg-ssh wrapper script on the volume.
 * This script proxies all imsg CLI commands to the remote Mac via SSH.
 */
function createImsgSshScript(remoteHost) {
  const scriptsDir = resolve(ROOT, ".tmpdata", "scripts");
  mkdirSync(scriptsDir, { recursive: true });

  const scriptPath = resolve(scriptsDir, "imsg-ssh");
  const script = `#!/bin/bash
# imsg-ssh — proxy imsg commands to a remote Mac via SSH (Tailscale)
# Auto-generated by pnpm setup:local — do not edit manually
set -euo pipefail

REMOTE_HOST="${remoteHost}"
SSH_KEY="${SSH_KEY}"
KNOWN_HOSTS="${SSH_KNOWN_HOSTS}"

SSH_OPTS="-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=\$KNOWN_HOSTS -o ConnectTimeout=10 -i \$SSH_KEY"

# ── Handle file transfers for send --file ────────────────────────────────────
# When sending attachments, the file exists locally in the container.
# We need to SCP it to the Mac first, then run imsg send with the remote path.
args=("$@")
file_idx=-1

for i in "\${!args[@]}"; do
  if [[ "\${args[\$i]}" == "--file" ]]; then
    file_idx=$((i + 1))
    break
  fi
done

if [[ \$file_idx -ge 0 && \$file_idx -lt \${#args[@]} ]]; then
  local_file="\${args[\$file_idx]}"
  if [[ -f "\$local_file" ]]; then
    remote_tmp="/tmp/imsg-transfer-\$(basename "\$local_file")"
    scp \$SSH_OPTS "\$local_file" "\$REMOTE_HOST:\$remote_tmp" >/dev/null 2>&1
    args[\$file_idx]="\$remote_tmp"
  fi
fi

# ── Forward command to remote imsg ───────────────────────────────────────────
# Use explicit PATH so Homebrew binaries (/opt/homebrew/bin) are available over SSH
exec ssh \$SSH_OPTS "\$REMOTE_HOST" "export PATH=/opt/homebrew/bin:/usr/local/bin:\\\$PATH; imsg \${args[*]}"
`;

  writeFileSync(scriptPath, script, { mode: 0o755 });
  return scriptPath;
}

/**
 * Patch the iMessage channel config into openclaw.json on the shared volume.
 */
function patchImessageChannel({ remoteHost, dbPath }) {
  if (!existsSync(OPENCLAW_JSON)) {
    throw new Error("openclaw.json not found — has the setup wizard been completed?");
  }

  const config = JSON.parse(readFileSync(OPENCLAW_JSON, "utf8"));
  config.channels ??= {};

  config.channels.imessage = {
    enabled: true,
    cliPath: IMSG_CLI_PATH,
    dbPath,
    remoteHost,
    dmPolicy: "open",
    allowFrom: ["*"],
    groupPolicy: "allowlist",
    includeAttachments: true,
  };

  writeFileSync(OPENCLAW_JSON, JSON.stringify(config, null, 2) + "\n", "utf8");
}

export async function configureImessage(vars) {
  const wantsImessage = guardCancel(
    await confirm({
      message: "Configure iMessage channel?",
      initialValue: false,
    })
  );

  if (!wantsImessage) {
    log.info("Skipping iMessage configuration");
    return;
  }

  // ── Collect remote host (Tailscale) ────────────────────────────────────────
  const remoteHost = guardCancel(
    await text({
      message: "Remote Mac host via Tailscale (user@tailscale-ip)",
      placeholder: "user@100.66.210.88",
      validate: (v) => {
        if (!v?.trim()) return "Remote host is required";
        if (!v.includes("@")) return "Must be in user@host format (e.g. frionaai@100.66.210.88)";
      },
    })
  ).trim();

  // ── Collect DB path ────────────────────────────────────────────────────────
  const remoteUser = remoteHost.split("@")[0];
  const defaultDbPath = `/Users/${remoteUser}${DEFAULT_DB_PATH_SUFFIX}`;

  const dbPath = guardCancel(
    await text({
      message: "chat.db path on the remote Mac",
      placeholder: defaultDbPath,
      initialValue: defaultDbPath,
      validate: (v) => {
        if (!v?.trim()) return "DB path is required";
        if (!v.endsWith("chat.db")) return "Path should end with chat.db";
      },
    })
  ).trim();

  // ── Step 1: Generate SSH key pair ──────────────────────────────────────────
  let pubKey;
  {
    const s = spinner();
    s.start("Generating SSH key pair in container…");
    try {
      pubKey = await ensureSshKey();
      s.stop("SSH key ready ✓");
    } catch (err) {
      s.stop("Failed to generate SSH key");
      log.error(`  ${err.message}`);
      return;
    }
  }

  // ── Step 2: Show public key + Mac prerequisites ────────────────────────────
  note(
    [
      "  Before continuing, set up the Mac Studio:",
      "",
      "  1. Install imsg CLI (if not already installed):",
      "       brew install steipete/tap/imsg",
      "",
      "  2. Grant Full Disk Access to Terminal in:",
      "       System Settings > Privacy & Security > Full Disk Access",
      "",
      "  3. Ensure Tailscale is running on the Mac",
      "",
      "  4. Add this public key to the Mac's authorized_keys:",
      "",
      `       ${pubKey}`,
      "",
      "     Quick command (run on the Mac):",
      `       echo '${pubKey}' >> ~/.ssh/authorized_keys`,
    ].join("\n"),
    "Mac Studio prerequisites"
  );

  guardCancel(
    await confirm({
      message: "Public key added to Mac and prerequisites met?",
      initialValue: false,
    })
  );

  // ── Step 3: Test SSH connectivity ──────────────────────────────────────────
  {
    const s = spinner();
    s.start(`Testing SSH connection to ${remoteHost}…`);
    try {
      const output = await testSshConnectivity(remoteHost);
      if (output.includes("__IMSG_NOT_FOUND__")) {
        s.stop("SSH works but imsg CLI not found on Mac");
        log.warn("  Install it: brew install steipete/tap/imsg");
        log.warn("  Continuing anyway — you can install it later.");
      } else {
        s.stop(`SSH connection to ${remoteHost} verified ✓`);
      }
    } catch (err) {
      s.stop("SSH connection failed");
      log.warn(`  ${err.message}`);
      const continueAnyway = guardCancel(
        await confirm({
          message: "SSH test failed. Continue with iMessage setup anyway?",
          initialValue: false,
        })
      );
      if (!continueAnyway) {
        log.info("Skipping iMessage configuration");
        return;
      }
    }
  }

  // ── Step 4: Create imsg-ssh wrapper script ─────────────────────────────────
  {
    const s = spinner();
    s.start("Creating imsg-ssh wrapper script…");
    try {
      createImsgSshScript(remoteHost);
      s.stop("imsg-ssh script created at /data/scripts/imsg-ssh ✓");
    } catch (err) {
      s.stop("Failed to create imsg-ssh script");
      log.error(`  ${err.message}`);
      return;
    }
  }

  // ── Step 5: Patch openclaw.json ────────────────────────────────────────────
  {
    const s = spinner();
    s.start("Writing iMessage channel config to openclaw.json…");
    try {
      patchImessageChannel({ remoteHost, dbPath });
      s.stop("iMessage channel configured ✓");
    } catch (err) {
      s.stop("Failed to write iMessage config");
      log.error(`  ${err.message}`);
      return;
    }
  }

  log.success(
    [
      "iMessage channel settings:",
      `  remoteHost: ${remoteHost}`,
      `  dbPath:     ${dbPath}`,
      `  cliPath:    ${IMSG_CLI_PATH}`,
    ].join("\n")
  );

  // ── Step 6: Restart container ──────────────────────────────────────────────
  {
    const s = spinner();
    s.start("Restarting container to apply iMessage config…");
    try {
      await execFileAsync("docker", ["restart", CONTAINER_NAME], { timeout: 30_000 });
      s.stop("Container restarted ✓");
    } catch (err) {
      s.stop("Container restart failed");
      log.warn(`  ${err.message}`);
      log.warn(`  Run manually: docker restart ${CONTAINER_NAME}`);
      return;
    }
  }

  // ── Wait for gateway ───────────────────────────────────────────────────────
  {
    const port = vars.PORT ?? "8080";
    const healthUrl = `http://localhost:${port}/setup/healthz`;
    const s = spinner();
    s.start("Waiting for gateway to come back up…");
    const healthy = await pollHealth(healthUrl, 60_000);
    if (healthy) {
      s.stop("Gateway is ready — iMessage channel active ✓");
    } else {
      s.stop("Gateway health check timed out — it may still be starting up");
      log.warn(`  Monitor with: docker logs -f ${CONTAINER_NAME}`);
    }
  }
}
