import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { ENV_PATH } from "./constants.mjs";

export function parseEnvFile(path = ENV_PATH) {
  if (!existsSync(path)) return {};
  const vars = {};
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq === -1) continue;
    vars[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
  }
  return vars;
}

export function buildEnvContent(v) {
  return [
    "# =============================================================================",
    "# Frontiers Market Bot — generated by scripts/setup/index.mjs",
    "# =============================================================================",
    "",
    "# Password to access the /setup wizard",
    `SETUP_PASSWORD=${v.SETUP_PASSWORD ?? ""}`,
    "",
    "# OpenClaw state & workspace dirs (volume mount inside container)",
    `OPENCLAW_STATE_DIR=${v.OPENCLAW_STATE_DIR ?? "/data/.openclaw"}`,
    `OPENCLAW_WORKSPACE_DIR=${v.OPENCLAW_WORKSPACE_DIR ?? "/data/workspace"}`,
    "",
    "# Bearer token for the gateway — stable across restarts",
    `OPENCLAW_GATEWAY_TOKEN=${v.OPENCLAW_GATEWAY_TOKEN ?? ""}`,
    "",
    "# Wrapper listen port (default: 8080)",
    `PORT=${v.PORT ?? "8080"}`,
    "",
    "# Enable browser-based terminal at /tui",
    `ENABLE_WEB_TUI=${v.ENABLE_WEB_TUI ?? "false"}`,
    "",
    "# Internal gateway port (usually no need to change)",
    `INTERNAL_GATEWAY_PORT=${v.INTERNAL_GATEWAY_PORT ?? "18789"}`,
    "",
    "# Ranch UUID this bot is scoped to (set by pnpm setup:local → scope step)",
    `RANCH_UUID=${v.RANCH_UUID ?? ""}`,
    "",
  ].join("\n");
}

export function writeEnvFile(vars) {
  writeFileSync(ENV_PATH, buildEnvContent(vars), "utf8");
}
